export { OurStoryTimelineVariant } from './our-story-timeline-variant'
export { OurStoryCardsVariant } from './our-story-cards-variant'
export { OurStoryMinimalVariant } from './our-story-minimal-variant'
export { OurStoryZigzagVariant } from './our-story-zigzag-variant'
export { OurStoryBookletVariant } from './our-story-booklet-variant'
export type { BaseOurStoryProps, Photo, TimelineEvent } from './types'